// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetOptimizerParserApi.DbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetOptimizerParserApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420003611_RemovedSomeshitInQosInSwitch")]
    partial class RemovedSomeshitInQosInSwitch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.CommutatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("boolean");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SwitchRoleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CommutatorsTable");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.PcEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PcTable");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.RouterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RoutersTable");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.CommutatorEntity", b =>
                {
                    b.OwnsOne("NetOptimizerParserApi.Models.Components.PoeSpecs", "PoeSpecs", b1 =>
                        {
                            b1.Property<int>("CommutatorEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("PoeBudgetW")
                                .HasColumnType("integer");

                            b1.Property<bool>("SupportsPoe")
                                .HasColumnType("boolean");

                            b1.HasKey("CommutatorEntityId");

                            b1.ToTable("CommutatorsTable");

                            b1.WithOwner()
                                .HasForeignKey("CommutatorEntityId");
                        });

                    b.OwnsOne("NetOptimizerParserApi.Models.Components.SwitchPerformanceSpecs", "PerformanceSpecs", b1 =>
                        {
                            b1.Property<int>("CommutatorEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("MacTableSize")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxVlans")
                                .HasColumnType("integer");

                            b1.Property<decimal>("ThroughputGbps")
                                .HasColumnType("numeric");

                            b1.HasKey("CommutatorEntityId");

                            b1.ToTable("CommutatorsTable");

                            b1.WithOwner()
                                .HasForeignKey("CommutatorEntityId");
                        });

                    b.OwnsOne("NetOptimizerParserApi.Models.Components.SwitchProtocolSupport", "ProtocolSupport", b1 =>
                        {
                            b1.Property<int>("CommutatorEntityId")
                                .HasColumnType("integer");

                            b1.Property<bool>("SupportsLacp")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsLag")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsLoopProtection")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsQos")
                                .HasColumnType("boolean");

                            b1.HasKey("CommutatorEntityId");

                            b1.ToTable("CommutatorsTable");

                            b1.WithOwner()
                                .HasForeignKey("CommutatorEntityId");
                        });

                    b.OwnsMany("NetOptimizerParserApi.Models.Port", "Ports", b1 =>
                        {
                            b1.Property<int>("CommutatorEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Count");

                            b1.Property<string>("Speed")
                                .IsRequired();

                            b1.Property<bool>("SupportsPoe");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("CommutatorEntityId", "__synthesizedOrdinal");

                            b1.ToTable("CommutatorsTable");

                            b1
                                .ToJson("Ports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CommutatorEntityId");
                        });

                    b.Navigation("PerformanceSpecs")
                        .IsRequired();

                    b.Navigation("PoeSpecs")
                        .IsRequired();

                    b.Navigation("Ports");

                    b.Navigation("ProtocolSupport")
                        .IsRequired();
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.PcEntity", b =>
                {
                    b.OwnsOne("NetOptimizerParserApi.Models.Components.PcHardwareSpecs", "HardwareSpecs", b1 =>
                        {
                            b1.Property<int>("PcEntityId")
                                .HasColumnType("integer");

                            b1.Property<string>("CpuModel")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RamAmountGb")
                                .HasColumnType("integer");

                            b1.Property<string>("RamType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("StorageAmountGb")
                                .HasColumnType("integer");

                            b1.Property<string>("StorageType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PcEntityId");

                            b1.ToTable("PcTable");

                            b1.WithOwner()
                                .HasForeignKey("PcEntityId");
                        });

                    b.OwnsOne("NetOptimizerParserApi.Models.Components.PcWifiOptions", "WifiOptions", b1 =>
                        {
                            b1.Property<int>("PcEntityId")
                                .HasColumnType("integer");

                            b1.Property<bool>("HasWiFi")
                                .HasColumnType("boolean");

                            b1.HasKey("PcEntityId");

                            b1.ToTable("PcTable");

                            b1.WithOwner()
                                .HasForeignKey("PcEntityId");
                        });

                    b.OwnsMany("NetOptimizerParserApi.Models.Port", "Ports", b1 =>
                        {
                            b1.Property<int>("PcEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Count");

                            b1.Property<string>("Speed")
                                .IsRequired();

                            b1.Property<bool>("SupportsPoe");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PcEntityId", "__synthesizedOrdinal");

                            b1.ToTable("PcTable");

                            b1
                                .ToJson("Ports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PcEntityId");
                        });

                    b.Navigation("HardwareSpecs")
                        .IsRequired();

                    b.Navigation("Ports");

                    b.Navigation("WifiOptions")
                        .IsRequired();
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.RouterEntity", b =>
                {
                    b.OwnsOne("NetOptimizerParserApi.Models.Components.RouterPerformanceSpecs", "PerformanceSpecs", b1 =>
                        {
                            b1.Property<int>("RouterEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("FlashMb")
                                .HasColumnType("integer");

                            b1.Property<int>("RamMb")
                                .HasColumnType("integer");

                            b1.Property<double>("RoutingThroughputGbps")
                                .HasColumnType("double precision");

                            b1.HasKey("RouterEntityId");

                            b1.ToTable("RoutersTable");

                            b1.WithOwner()
                                .HasForeignKey("RouterEntityId");
                        });

                    b.OwnsOne("NetOptimizerParserApi.Models.Components.RouterProtocolSupport", "ProtocolSupport", b1 =>
                        {
                            b1.Property<int>("RouterEntityId")
                                .HasColumnType("integer");

                            b1.Property<bool>("SupportsIpsec")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsNat")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsOspf")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SupportsVrrp")
                                .HasColumnType("boolean");

                            b1.HasKey("RouterEntityId");

                            b1.ToTable("RoutersTable");

                            b1.WithOwner()
                                .HasForeignKey("RouterEntityId");
                        });

                    b.OwnsOne("NetOptimizerParserApi.Models.Components.WifiOptions", "WifiOptions", b1 =>
                        {
                            b1.Property<int>("RouterEntityId")
                                .HasColumnType("integer");

                            b1.Property<int>("AntennaCount")
                                .HasColumnType("integer");

                            b1.Property<double>("AntennaGain")
                                .HasColumnType("double precision");

                            b1.Property<string>("FrequencyBands")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("HasWiFi")
                                .HasColumnType("boolean");

                            b1.Property<double>("MaxWirelessSpeed")
                                .HasColumnType("double precision");

                            b1.Property<string>("WiFiStandard")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RouterEntityId");

                            b1.ToTable("RoutersTable");

                            b1.WithOwner()
                                .HasForeignKey("RouterEntityId");
                        });

                    b.OwnsMany("NetOptimizerParserApi.Models.Port", "Ports", b1 =>
                        {
                            b1.Property<int>("RouterEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Count");

                            b1.Property<string>("Speed")
                                .IsRequired();

                            b1.Property<bool>("SupportsPoe");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("RouterEntityId", "__synthesizedOrdinal");

                            b1.ToTable("RoutersTable");

                            b1
                                .ToJson("Ports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RouterEntityId");
                        });

                    b.Navigation("PerformanceSpecs");

                    b.Navigation("Ports");

                    b.Navigation("ProtocolSupport");

                    b.Navigation("WifiOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
