// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetOptimizerParserApi.DbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetOptimizerParserApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307232807_AddedRoutersTable")]
    partial class AddedRoutersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.CommutatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("SupportsPoe")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CommutatorsTable");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.RouterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AntennaCount")
                        .HasColumnType("integer");

                    b.Property<double>("AntennaGain")
                        .HasColumnType("double precision");

                    b.Property<decimal>("AvveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<double>("FirewallThroughputGbps")
                        .HasColumnType("double precision");

                    b.Property<string>("FrequencyBands")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSessions")
                        .HasColumnType("integer");

                    b.Property<double>("MaxWirelessSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PowerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsBgp")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsIpsec")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsMpls")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsNat")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsOspf")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVrrp")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("VpnThroughputMbps")
                        .HasColumnType("double precision");

                    b.Property<string>("WiFiStandard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoutersTable");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.CommutatorEntity", b =>
                {
                    b.OwnsMany("NetOptimizerParserApi.Models.Port", "Ports", b1 =>
                        {
                            b1.Property<int>("CommutatorEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Count");

                            b1.Property<string>("Speed")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("CommutatorEntityId", "__synthesizedOrdinal");

                            b1.ToTable("CommutatorsTable");

                            b1
                                .ToJson("Ports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CommutatorEntityId");
                        });

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("NetOptimizerParserApi.Models.DbEntities.RouterEntity", b =>
                {
                    b.OwnsMany("NetOptimizerParserApi.Models.Port", "Ports", b1 =>
                        {
                            b1.Property<int>("RouterEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Count");

                            b1.Property<string>("Speed")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("RouterEntityId", "__synthesizedOrdinal");

                            b1.ToTable("RoutersTable");

                            b1
                                .ToJson("Ports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RouterEntityId");
                        });

                    b.Navigation("Ports");
                });
#pragma warning restore 612, 618
        }
    }
}
